### ISSUE TITLE
set controlnet_threshold_a/b as parameters 

### ISSUE THREAD

**Issue by trikpachu** [sjaak31367/a1111-controlnet-batch-preprocessor#1]
Hi, great tool :)

I recommend putting the two parameters controlnet_threshold_a/b, which currently take a default value of 64 in string form, as parameters in the beginning, with a line of explanation. This will help idiots like me, as it took me some time discovering why the result of depth preprocessing was so terrible at first as the default value for these thresholds should've been 0 in this case.

**Comment by sjaak31367** [comment]
Thank you!  
And my apologies, scripts/code makes a lot more sense when you're the one who wrote it, so it's easy to forget how others will see it. 😅  
I'll try to refactor it, and correct the default values where applicable, thank you for pointing it out!

**Comment by sjaak31367** [comment]
It's quite a bit less readable now, but you can now specify preprocessor arguments via the command line arguments.  
Do `-h` to view a simple help message, `-c [controlnet] -l` to view available ones for the preprocessor used.  
And do `-a [float or int]` and `-b [float or int]` to set them. If none are specified, they will detect and use the default values.  
Apologies for the delay, but stuff happens sometimes.  
Have a good one, and hopefully it's to usability and satisfaction! :)
